"""Strict audit of a bounded synthetic worker ledger; no backend access."""
from __future__ import annotations

import copy
import hashlib
import json


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(',', ':')).encode()).hexdigest()


def audit(record):
    """Return unknown on incomplete identity/lifecycle evidence, never infer from POSTs."""
    try:
        if record.get('closed') is not True or not record.get('operation_id'):
            raise ValueError('window or operation identity missing')
        if not record.get('epoch') or not record.get('snapshots'):
            raise ValueError('epoch or snapshot boundaries missing')
        unique = {}
        for snapshot in record['snapshots']:
            if snapshot['first_seq'] != 1 or snapshot['last_seq'] != len(snapshot['events']):
                raise ValueError('incomplete snapshot')
            if sorted(e['seq'] for e in snapshot['events']) != list(range(1, snapshot['last_seq'] + 1)):
                raise ValueError('snapshot sequence gap')
            for e in snapshot['events']:
                if any(not e.get(k) for k in ('event_id', 'run_id', 'call_id', 'attempt_id')):
                    raise ValueError('identity missing')
                if e['operation_id'] != record['operation_id'] or e['epoch'] != record['epoch']:
                    raise ValueError('identity changed')
                if not isinstance(e['monotonic_ns'], int):
                    raise ValueError('clock missing')
                key = e['event_id']
                if key in unique and unique[key] != e:
                    raise ValueError('event ID conflict')
                unique[key] = e
        events = sorted(unique.values(), key=lambda x: x['seq'])
        if [e['seq'] for e in events] != list(range(1, record['final_seq'] + 1)):
            raise ValueError('ledger sequence gap')
        if any(a['monotonic_ns'] > b['monotonic_ns'] for a, b in zip(events, events[1:])):
            raise ValueError('clock reversal')
        if not events or events[-1]['kind'] != 'window_closed':
            raise ValueError('close witness missing')
        accepted, starts, terminal = {}, {}, {}
        for e in events:
            kind = e['kind']
            if kind in ('accepted', 'execution_start', 'terminal') and not e.get('job_id'):
                raise ValueError('job ID missing')
            if kind == 'accepted':
                if e['job_id'] in accepted:
                    raise ValueError('duplicate acceptance identity')
                accepted[e['job_id']] = e
            elif kind == 'execution_start':
                job = accepted.get(e['job_id'])
                if not job or job['seq'] >= e['seq'] or not e.get('execution_id'):
                    raise ValueError('unbound execution')
                if e['execution_id'] in starts:
                    raise ValueError('execution ID reused')
                if any(e[k] != job[k] for k in ('run_id','call_id','attempt_id')):
                    raise ValueError('execution owner mismatch')
                starts[e['execution_id']] = e
            elif kind == 'terminal':
                start = starts.get(e.get('execution_id'))
                if not start or start['seq'] >= e['seq'] or e['execution_id'] in terminal:
                    raise ValueError('terminal without unique start')
                if any(e[k] != start[k] for k in ('job_id','run_id','call_id','attempt_id')):
                    raise ValueError('terminal owner mismatch')
                if 'node' not in e or e['node'] is not None or e.get('history_completed') is not True:
                    raise ValueError('terminal discriminator missing')
                hashes = e.get('artifact_sha256')
                if not hashes or any(len(h) != 64 or any(c not in '0123456789abcdef' for c in h) for h in hashes):
                    raise ValueError('artifact receipt missing')
                terminal[e['execution_id']] = e
        if set(starts) != set(terminal) or {s['job_id'] for s in starts.values()} != set(accepted):
            raise ValueError('incomplete accepted job lifecycle')
        return {'state': 'verified', 'executions': len(starts), 'reason': 'closed synthetic lifecycle'}
    except (KeyError, TypeError, ValueError) as error:
        return {'state': 'unknown', 'executions': None, 'reason': str(error)}


def constructed_checks():
    """Hand-specified expected states for 20 fixtures, not generated by audit."""
    common = dict(operation_id='op', run_id='run', call_id='call', attempt_id='attempt', epoch='epoch')
    events = []
    for i, kind in enumerate(('accepted','execution_start','terminal','window_closed'), 1):
        e = dict(common, kind=kind, seq=i, event_id=f'e{i}', monotonic_ns=i, job_id='job')
        if kind in ('execution_start','terminal'):
            e['execution_id'] = 'execution'
        if kind == 'terminal':
            e.update(node=None, history_completed=True, artifact_sha256=['a'*64])
        events.append(e)
    base = dict(operation_id='op', epoch='epoch', closed=True, final_seq=4,
                snapshots=[dict(first_seq=1,last_seq=4,events=events)])
    cases = []
    def add(name, value, expected, count=None):
        cases.append(dict(name=name, record=value, expected_state=expected, expected_executions=count))
    add('complete', copy.deepcopy(base), 'verified', 1)
    v=copy.deepcopy(base);v['snapshots']*=2;add('duplicate_snapshot',v,'verified',1)
    v=copy.deepcopy(base);v['snapshots'][0]['events'].reverse();add('arrival_order_reversed',v,'verified',1)
    v=copy.deepcopy(base);v['snapshots'].insert(0,dict(first_seq=1,last_seq=2,events=copy.deepcopy(events[:2])));add('cumulative_snapshots',v,'verified',1)
    for field in ('operation_id','run_id','call_id','attempt_id','event_id','epoch','monotonic_ns'):
        v=copy.deepcopy(base);del v['snapshots'][0]['events'][1][field];add('missing_'+field,v,'unknown')
    for name, field, value in [('missing_terminal_node','node','DELETE'),('nonnull_terminal_node','node','node-1'),('incomplete_history','history_completed',False),('missing_artifact','artifact_sha256',[])]:
        v=copy.deepcopy(base)
        if value=='DELETE': del v['snapshots'][0]['events'][2][field]
        else:v['snapshots'][0]['events'][2][field]=value
        add(name,v,'unknown')
    v=copy.deepcopy(base);v['snapshots'][0]['events'].pop(1);add('missing_event',v,'unknown')
    v=copy.deepcopy(base);del v['snapshots'][0]['last_seq'];add('missing_snapshot_boundary',v,'unknown')
    v=copy.deepcopy(base);v['snapshots'][0]['events'][2]['epoch']='restarted';add('restart_without_binding',v,'unknown')
    v=copy.deepcopy(base);v['snapshots'].append(copy.deepcopy(v['snapshots'][0]));v['snapshots'][1]['events'][1]['job_id']='conflict';add('conflicting_duplicate',v,'unknown')
    v=copy.deepcopy(base);v['closed']=False;add('open_window',v,'unknown')
    for case in cases:
        case['actual']=audit(case['record'])
        case['passed']=case['actual']['state']==case['expected_state'] and case['actual']['executions']==case['expected_executions']
    return cases
